name: Deploy Website to S3 and Invalidate CloudFront

on:
  push:
    branches:
      - main # This workflow runs when you push to the 'main' branch

env:
  AWS_REGION: ap-south-1 # Make sure this is the region where your S3 bucket is located
  S3_BUCKET_NAME: ${{ secrets.AWS_S3_BUCKET }}
  CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID }}

permissions:
  id-token: write # This is important for OIDC, but also needed for temporary credentials
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy static files to S3
        run: |
          aws s3 sync . s3://${{ env.S3_BUCKET_NAME }} --delete --exclude ".git/*" --exclude ".github/*" --exclude "node_modules/*" --exclude "package.json" --exclude "package-lock.json"

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ env.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"